services:
  database:
    container_name: loan_api_database
    image: postgres:16.3
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: loan_api_app
    build:
      context: .
    volumes:
      - .:/code
    env_file: .env
    environment:
      DATABASE_URL: postgres://loanuser:loanpass@database:5432/loandb
    depends_on:
      database:
        condition: service_healthy

  nginx:
    container_name: loan_api_nginx
    image: nginx:1.27.0
    restart: no
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/code/staticfiles  # mapping staticfiles so nginx can find them to serve;
    depends_on:
      - app
