services:
  database:
    container_name: loan_api_prod_db
    image: postgres:16.3
    restart: on-failure:3
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: loan_api_prod_app
    image: loan_api:1.0.0
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

  nginx:
    container_name: loan_api_prod_nginx
    image: nginx:1.27.0
    restart: on-failure:3
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/code/staticfiles  # mapping staticfiles so nginx can find them to serve;
    depends_on:
      - app

volumes:
  pgdata: