# Generated by Django 5.0.6 on 2024-07-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('interest_rate', models.FloatField()),
                ('ip_address', models.CharField(max_length=128)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('client', models.CharField(max_length=64)),
                ('installments', models.PositiveSmallIntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loan')),
            ],
        ),
    ]
