# Generated by Django 5.0.6 on 2024-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ip_address',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
