# Generated by Django 5.0.7 on 2024-07-18 08:08

import loan_api.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_alter_loan_value_alter_payment_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=11,
                                      validators=[loan_api.base.validators.positive_value]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=11,
                                      validators=[loan_api.base.validators.positive_value]),
        ),
    ]
