# Generated by Django 5.0.7 on 2024-07-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_loan_request_date_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
