# Generated by Django 5.0.7 on 2024-07-22 22:27

import loan_api.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_alter_loan_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4,
                                      validators=[loan_api.base.validators.non_negative_interest_rate]),
        ),
    ]
